### ISSUE TITLE
Feedback agent in lg-mainloop crashes after post 1

### ISSUE THREAD

**Issue by onlyjazz** [onlyjazz/book-launch#9]
```
Running the Save content agent

Query ran at 2024-10-22 19:49 | Query: *[_type == "cycle"]{round} | Returned Status: 200 | Response Length: 95
Query ran at 2024-10-22 19:50 | Query: *[_type == "prompt" && cycle == 8]{cta} | Returned Status: 200 | Response Length: 346
Query ran at 2024-10-22 19:50 | Query: *[_type == "cycle"]{round} | Returned Status: 200 | Response Length: 95
Query ran at 2024-10-22 19:50 | Query: *[_type == "prompt" && cycle==8].identifier | Returned Status: 200 | Response Length: 119
Query ran at 2024-10-22 19:50 | Query:  "patch": {"create": doc) | Returned Status: 200 | Response Length: 77
Query ran at 2024-10-22 19:50 | Query: *[_type == "cycle"]{round} | Returned Status: 200 | Response Length: 95
Query ran at 2024-10-22 19:50 | Query: math::max(*[_type == "prompt"].cycle) | Returned Status: 200 | Response Length: 94
Running the Feedback content agent at round 8
Query ran at 2024-10-22 19:50 | Query: *[_type == "post" && !(_id in path("drafts.**"))] | order(header asc) { _id, tweet_id, header } | Returned Status: 200 | Response Length: 3341
Query returned  20 published posts
1 header Are you telling a narrative or your truth?, tweet_id 1845417351337938965, doc_id 1e2c8dc0-4689-439a-ac43-3919928fc604, engagement_rate 0.0, impression_count 8
Query ran at 2024-10-22 19:50 | Query:  "patch": {"id": doc_id,"set": {"impression_count": impression_count, "engagement_rate": engagement_rate } | Returned Status: 200 | Response Length: 77
Feedback content agent processed  20  posts
Query ran at 2024-10-22 19:51 | Query: *[_type == "prompt"]{_id, identifier} | Returned Status: 200 | Response Length: 868
Query ran at 2024-10-22 19:51 | Query: *[_type == "post"]{prompt_identifier, impression_count, engagement_rate} | Returned Status: 200 | Response Length: 1853
Traceback (most recent call last):
  File "/Users/admin/code/book-launch/lg-mainloop.py", line 126, in <module>
    final_state = app.invoke(
                  ^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.12.5/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1551, in invoke
    for chunk in self.stream(
                 ^^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.12.5/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1290, in stream
    for _ in runner.tick(
             ^^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.12.5/lib/python3.12/site-packages/langgraph/pregel/runner.py", line 56, in tick
    run_with_retry(t, retry_policy)
  File "/Users/admin/.pyenv/versions/3.12.5/lib/python3.12/site-packages/langgraph/pregel/retry.py", line 29, in run_with_retry
    task.proc.invoke(task.input, config)
  File "/Users/admin/.pyenv/versions/3.12.5/lib/python3.12/site-packages/langgraph/utils/runnable.py", line 385, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.12.5/lib/python3.12/site-packages/langgraph/utils/runnable.py", line 167, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/code/book-launch/lg-mainloop.py", line 66, in save_content
    feedback_agent_run()
  File "/Users/admin/code/book-launch/bl_sanity_utils.py", line 428, in feedback_agent_run
    feedback_agent_prompt_stats()
  File "/Users/admin/code/book-launch/bl_sanity_utils.py", line 402, in feedback_agent_prompt_stats
    aggregates[identifier]['impression_count'] += post_document['impression_count']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by onlyjazz** [comment]
indentation in the wrong place

```
            continue
        time.sleep(64)  # Wait for 64s

    return published_posts
```
